#!/usr/bin/env sh
# Build two sample rushes with ffmpeg, into ./work/in/.
#
# Why synthesised rather than downloaded: a URL to stock footage rots, and its licence has to be
# re-checked by every reader. ffmpeg's own test sources are deterministic, need no network, and
# raise no rights question at all — so this example still runs identically in five years.
#
# Replace them with your own footage whenever you like; nothing below depends on their content.
set -eu

DIR="$(cd "$(dirname "$0")/.." && pwd)/work/in"
FFMPEG="${FFMPEG_PATH:-ffmpeg}"
mkdir -p "$DIR"

"$FFMPEG" -v error -y \
  -f lavfi -i "testsrc2=size=640x360:rate=25:duration=4" \
  -f lavfi -i "sine=frequency=300:duration=4" \
  -c:v libx264 -pix_fmt yuv420p -c:a aac -shortest "$DIR/rush1.mp4"

"$FFMPEG" -v error -y \
  -f lavfi -i "smptebars=size=640x360:rate=25:duration=4" \
  -f lavfi -i "sine=frequency=600:duration=4" \
  -c:v libx264 -pix_fmt yuv420p -c:a aac -shortest "$DIR/rush2.mp4"

echo "Wrote:"
ls -l "$DIR/rush1.mp4" "$DIR/rush2.mp4"
echo
echo "Both are generated by ffmpeg itself. No third-party content, no licence to track."
