#!/usr/bin/env sh
# Build two sample rushes into ./work/in/.
#
# Why synthesised rather than downloaded: a stock-footage URL rots, and its licence has to be
# re-checked by every reader. ffmpeg's own test sources are deterministic, need no network, and
# raise no rights question at all — so this example runs identically anywhere, today and later.
#
# Uses your local ffmpeg if you have one, and the Docker image otherwise, so you do not need to
# install anything to try the walkthrough.
#
# Replace the rushes with your own footage whenever you like; nothing below depends on what they
# show.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/work/in"
IMAGE="${ATELIER_IMAGE:-video-atelier-mcp:0.1.0}"
mkdir -p "$DIR"

if command -v "${FFMPEG_PATH:-ffmpeg}" >/dev/null 2>&1; then
  run_ffmpeg() { "${FFMPEG_PATH:-ffmpeg}" "$@"; }
  echo "Using local ffmpeg."
elif docker image inspect "$IMAGE" >/dev/null 2>&1; then
  run_ffmpeg() { docker run --rm -v "$ROOT/work:/work" --entrypoint ffmpeg "$IMAGE" "$@"; }
  DIR="/work/in"
  echo "No local ffmpeg; using $IMAGE."
else
  echo "Need either ffmpeg on PATH or the $IMAGE image (docker compose build)." >&2
  exit 1
fi

run_ffmpeg -v error -y \
  -f lavfi -i "testsrc2=size=640x360:rate=25:duration=4" \
  -f lavfi -i "sine=frequency=300:duration=4" \
  -c:v libx264 -pix_fmt yuv420p -c:a aac -shortest "$DIR/rush1.mp4"

run_ffmpeg -v error -y \
  -f lavfi -i "smptebars=size=640x360:rate=25:duration=4" \
  -f lavfi -i "sine=frequency=600:duration=4" \
  -c:v libx264 -pix_fmt yuv420p -c:a aac -shortest "$DIR/rush2.mp4"

echo "Wrote:"
ls -l "$ROOT/work/in/rush1.mp4" "$ROOT/work/in/rush2.mp4"
echo
echo "Both are generated by ffmpeg itself. No third-party content, no licence to track."
